In [66]:
import pandas as pd
import numpy as np

def print_full(df):
    # Set display options to show all columns
    pd.set_option('display.max_columns', None)  # Show all columns
    pd.set_option('display.max_rows', None)     # Show all rows
    pd.set_option('display.width', None)        # Auto-detect display width
    pd.set_option('display.max_colwidth', None) # Show full content of each column
    display(df)
    # Reset display options to default
    pd.reset_option('display.max_columns')
    pd.reset_option('display.max_rows')
    pd.reset_option('display.width')
    pd.reset_option('display.max_colwidth')

In [49]:
results_id = {
    "mat_type_a_1":"20250904-152518",
    "mat_type_b_1":"20250904-152058",
    "mat_type_a_2":"20250906-173524",
    "mat_type_b_2":"20250906-172413",
    "mat_type_a_3":"20250908-175440",
    "mat_type_b_3":"20250908-175725",
}
results_df = {}

In [50]:
for key, val in results_id.items():
    results_df[key] = pd.read_csv(f"./../Modules/output_processor/processed_results_{val}.csv")
    results_df[key][['instance_type', 'instance_id']] = results_df[key][['instance_type', 'instance_id']].astype(float)
    print(f"{key}: {results_df[key].shape}")

mat_type_a_1: (30, 44)
mat_type_b_1: (30, 59)
mat_type_a_2: (30, 59)
mat_type_b_2: (30, 59)
mat_type_a_3: (30, 59)
mat_type_b_3: (30, 59)

,instance_type_3,instance_id_3,distance_metric_3,total_demand_3,dom_rule_3,truck_capacity_3,fixed_setup_time_3,truck_speed_3,max_vehicles_3,max_nodes_proute_DP_3,...,bnb_sol_phase_3,bnb_termCond_3,bnb_upb_3,bnb_lwb_3,bnb_upb_in_min_per_pkg_3,bnb_lwb_in_min_per_pkg_3,bnb_gap_3,bnb_nodesExp_3,bnb_wallTime_3,bnb_bnpTimeLim_3
0,2.0,1.0,L2norm,26.558,4,20,0,20,inf,inf,...,2,optimality,21.1813,21.1813,47.85,47.85,0.0000,1,1.871141,7200
1,2.0,2.0,L2norm,28.116,4,20,0,20,inf,inf,...,2,optimality,27.1669,27.1669,57.97,57.97,0.0000,1,0.812982,7200
2,2.0,3.0,L2norm,40.966,4,20,0,20,inf,inf,...,2,optimality,36.2303,36.2303,53.06,53.06,-0.0000,1,1.550130,7200
3,2.0,4.0,L2norm,27.102,4,20,0,20,inf,inf,...,2,optimality,27.2315,27.2315,60.29,60.29,-0.0000,1,1.343376,7200
4,2.0,5.0,L2norm,36.133,4,20,0,20,inf,inf,...,2,optimality,32.1474,32.1474,53.38,53.38,0.0000,147,157.832005,7200
5,2.0,6.0,L2norm,33.310,4,20,0,20,inf,inf,...,2,optimality,31.5347,31.5347,56.80,56.80,0.0000,1,2.894194,7200
6,2.0,7.0,L2norm,28.826,4,20,0,20,inf,inf,...,2,optimality,25.5778,25.5778,53.24,53.24,0.0000,1,1.517954,7200
7,2.0,8.0,L2norm,26.935,4,20,0,20,inf,inf,...,2,optimality,22.9405,22.9405,51.10,51.10,-0.0000,1,1.365642,7200
8,2.0,9.0,L2norm,28.075,4,20,0,20,inf,inf,...,2,optimality,26.9711,26.9711,57.64,57.64,0.0000,1,2.375585,7200
9,2.0,10.0,L2norm,31.265,4,20,0,20,inf,inf,...,2,optimality,30.3297,30.3297,58.21,58.21,0.0000,1,1.412410,7200
10,2.0,1.0,L2norm,53.000,4,20,0,20,inf,inf,...,2,optimality,46.4467,46.4467,52.58,52.58,0.0000,17,1142.033178,7200
11,2.0,2.0,L2norm,61.606,4,20,0,20,inf,inf,...,2,optimality,60.7678,60.7678,59.18,59.18,0.0000,1,152.633219,7200
12,2.0,3.0,L2norm,61.475,4,20,0,20,inf,inf,...,2,optimality,58.9955,58.9955,57.58,57.58,0.0000,5,350.894152,7200
13,2.0,4.0,L2norm,48.834,4,20,0,20,inf,inf,...,2,optimality,47.5942,47.5942,58.48,58.48,0.0000,1,244.361802,7200
14,2.0,5.0,L2norm,70.345,4,20,0,20,inf,inf,...,2,time_limit,68.0199,66.1867,58.02,56.45,0.0277,208,7209.491376,7200
15,2.0,6.0,L2norm,52.529,4,20,0,20,inf,inf,...,2,optimality,47.6131,47.6131,54.38,54.38,0.0000,1,492.574646,7200
16,2.0,7.0,L2norm,68.590,4,20,0,20,inf,inf,...,2,optimality,67.3422,67.3422,58.91,58.91,0.0000,5,433.612781,7200
17,2.0,8.0,L2norm,74.241,4,20,0,20,inf,inf,...,2,time_limit,78.1879,77.6935,63.19,62.79,0.0064,353,7206.984518,7200
18,2.0,9.0,L2norm,67.105,4,20,0,20,inf,inf,...,2,optimality,68.3450,68.3450,61.11,61.11,0.0000,103,1111.566530,7200
19,2.0,10.0,L2norm,62.915,4,20,0,20,inf,inf,...,2,optimality,56.8315,56.8315,54.20,54.20,0.0000,317,5934.154851,7200
20,2.0,1.0,L2norm,83.413,4,20,0,20,inf,inf,...,2,time_limit,77.0086,76.0315,55.39,54.69,0.0129,10,18157.721114,18000
21,2.0,2.0,L2norm,75.333,4,20,0,20,inf,inf,...,2,time_limit,72.3306,71.8357,57.61,57.21,0.0069,47,18036.270230,18000
22,2.0,3.0,L2norm,87.550,4,20,0,20,inf,inf,...,2,time_limit,85.1361,83.5487,58.35,57.26,0.0190,13,18093.805059,18000
23,2.0,4.0,L2norm,99.879,4,20,0,20,inf,inf,...,2,time_limit,97.1235,93.8343,58.34,56.37,0.0351,48,18059.727471,18000
24,2.0,5.0,L2norm,76.319,4,20,0,20,inf,inf,...,2,time_limit,67.1618,65.4449,52.80,51.45,0.0262,6,18048.154899,18000
25,2.0,6.0,L2norm,86.269,4,20,0,20,inf,inf,...,2,optimality,82.3995,82.3995,57.31,57.31,0.0000,19,11054.698400,18000
26,2.0,7.0,L2norm,93.244,4,20,0,20,inf,inf,...,2,optimality,85.7051,85.7051,55.15,55.15,0.0000,1,2098.492593,18000
27,2.0,8.0,L2norm,100.130,4,20,0,20,inf,inf,...,2,time_limit,100.7241,97.6553,60.36,58.52,0.0314,47,18084.749815,18000
28,2.0,9.0,L2norm,87.172,4,20,0,20,inf,inf,...,2,time_limit,79.0842,76.6723,54.43,52.77,0.0315,13,18058.738045,18000
29,2.0,10.0,L2norm,100.884,4,20,0,20,inf,inf,...,2,time_limit,99.8580,93.2255,59.39,55.45,0.0711,4,18155.935807,18000

In [73]:
cmp_inst = [1,2,3]
ref_columns_base = ['instance_type','instance_id']
ref_columns = [f"{r}_{i}" for r in ref_columns_base for i in cmp_inst]
comparing_columns_base = ['bnb_upb', 'bnb_lwb',
                     'root_node_relaxObj', 'bnb_termCond',
                     "bnb_nodesExp", "bnb_gap", "bnb_wallTime"]
comparing_columns = [f"{c}_{i}" for c in comparing_columns_base for i in cmp_inst]

agg_df = pd.merge(pd.merge(results_df['mat_type_a_1'].add_suffix('_1', axis=1), results_df['mat_type_a_2'].add_suffix('_2', axis=1),how='inner',
         left_index=True, right_index=True), results_df['mat_type_a_3'].add_suffix('_3', axis=1), how='inner',
         left_index=True, right_index=True)[ref_columns+comparing_columns]
print_full(agg_df)
print_full(agg_df.loc[lambda x: x['bnb_termCond_3']!=x['bnb_termCond_2']])

,instance_type_1,instance_type_2,instance_type_3,instance_id_1,instance_id_2,instance_id_3,bnb_upb_1,bnb_upb_2,bnb_upb_3,bnb_lwb_1,bnb_lwb_2,bnb_lwb_3,root_node_relaxObj_1,root_node_relaxObj_2,root_node_relaxObj_3,bnb_termCond_1,bnb_termCond_2,bnb_termCond_3,bnb_nodesExp_1,bnb_nodesExp_2,bnb_nodesExp_3,bnb_gap_1,bnb_gap_2,bnb_gap_3,bnb_wallTime_1,bnb_wallTime_2,bnb_wallTime_3
0,2.0,2.0,2.0,1.0,1.0,1.0,21.1813,21.1813,21.1813,21.1813,21.1813,21.1813,21.181273,21.181273,21.181273,optimality,optimality,optimality,1.0,1.0,1,0.000000,0.0000,0.0000,2.028998,1.872481,1.871141
1,2.0,2.0,2.0,2.0,2.0,2.0,27.1669,27.1669,27.1669,27.1669,27.1669,27.1669,27.166882,27.166882,27.166882,optimality,optimality,optimality,1.0,1.0,1,0.000000,0.0000,0.0000,0.941376,0.824536,0.812982
2,2.0,2.0,2.0,3.0,3.0,3.0,36.2303,36.2303,36.2303,36.2303,36.2303,36.2303,36.230290,36.230290,36.230290,optimality,optimality,optimality,1.0,1.0,1,0.000000,-0.0000,-0.0000,1.666549,1.507536,1.550130
3,2.0,2.0,2.0,4.0,4.0,4.0,27.2315,27.2315,27.2315,27.2315,27.2315,27.2315,27.231500,27.231500,27.231500,optimality,optimality,optimality,1.0,1.0,1,0.000000,-0.0000,-0.0000,1.496961,1.300117,1.343376
4,2.0,2.0,2.0,5.0,5.0,5.0,32.2911,32.1474,32.1474,31.8883,31.8883,32.1474,31.215928,31.215928,31.215928,queue_empty,queue_empty,optimality,225.0,197.0,147,0.402831,0.0081,0.0000,260.924808,214.093049,157.832005
5,2.0,2.0,2.0,6.0,6.0,6.0,31.5347,31.5347,31.5347,31.5347,31.5347,31.5347,31.534664,31.534664,31.534664,optimality,optimality,optimality,1.0,1.0,1,0.000000,0.0000,0.0000,3.062988,2.871973,2.894194
6,2.0,2.0,2.0,7.0,7.0,7.0,25.5778,25.5778,25.5778,25.5778,25.5778,25.5778,25.577805,25.577805,25.577805,optimality,optimality,optimality,1.0,1.0,1,0.000000,0.0000,0.0000,1.692671,1.555557,1.517954
7,2.0,2.0,2.0,8.0,8.0,8.0,22.9405,22.9405,22.9405,22.9405,22.9405,22.9405,22.940520,22.940520,22.940520,optimality,optimality,optimality,1.0,1.0,1,0.000000,-0.0000,-0.0000,1.510276,1.361588,1.365642
8,2.0,2.0,2.0,9.0,9.0,9.0,26.9711,26.9711,26.9711,26.9711,26.9711,26.9711,26.971141,26.971141,26.971141,optimality,optimality,optimality,1.0,1.0,1,0.000000,0.0000,0.0000,2.528693,2.422663,2.375585
9,2.0,2.0,2.0,10.0,10.0,10.0,30.3297,30.3297,30.3297,30.3297,30.3297,30.3297,30.329694,30.329694,30.329694,optimality,optimality,optimality,1.0,1.0,1,0.000000,0.0000,0.0000,1.547523,1.439008,1.412410
10,2.0,2.0,2.0,1.0,1.0,1.0,46.4467,46.4467,46.4467,46.1730,46.1730,46.4467,46.172991,46.172991,46.172991,queue_empty,queue_empty,optimality,27.0,27.0,17,0.273695,0.0059,0.0000,1611.403424,1647.253790,1142.033178
11,2.0,2.0,2.0,2.0,2.0,2.0,60.7678,60.7678,60.7678,60.7678,60.7678,60.7678,60.767813,60.767813,60.767813,optimality,optimality,optimality,1.0,1.0,1,0.000000,0.0000,0.0000,158.400079,155.214535,152.633219
12,2.0,2.0,2.0,3.0,3.0,3.0,58.9955,58.9955,58.9955,58.9955,58.9955,58.9955,58.877588,58.877588,58.877588,optimality,optimality,optimality,5.0,3.0,5,0.000000,0.0000,0.0000,446.744315,313.237375,350.894152
13,2.0,2.0,2.0,4.0,4.0,4.0,47.5942,47.5942,47.5942,47.5942,47.5942,47.5942,47.594150,47.594150,47.594150,optimality,optimality,optimality,1.0,1.0,1,0.000000,0.0000,0.0000,248.195636,240.631971,244.361802
14,2.0,2.0,2.0,5.0,5.0,5.0,68.0199,68.0199,68.0199,66.3017,66.5214,66.1867,65.299413,65.299413,65.299413,time_limit,time_limit,time_limit,266.0,348.0,208,1.718254,0.0225,0.0277,7208.394329,7275.914666,7209.491376
15,2.0,2.0,2.0,6.0,6.0,6.0,47.6131,47.6131,47.6131,47.6131,47.6131,47.6131,47.613118,47.613118,47.613118,optimality,optimality,optimality,1.0,1.0,1,0.000000,0.0000,0.0000,497.312461,551.290028,492.574646
16,2.0,2.0,2.0,7.0,7.0,7.0,67.3422,67.3422,67.3422,67.3422,67.3422,67.3422,67.323723,67.323723,67.323723,optimality,optimality,optimality,5.0,5.0,5,0.000000,0.0000,0.0000,370.442327,339.256582,433.612781
17,NaN,2.0,2.0,NaN,8.0,8.0,NaN,78.1879,78.1879,NaN,78.1884,77.6935,NaN,75.261669,75.261669,NaN,optimality,time_limit,NaN,441.0,353,NaN,-0.0000,0.0064,NaN,3956.108821,7206.984518
18,2.0,2.0,2.0,9.0,9.0,9.0,68.6572,68.3450,68.3450,68.6602,68.3450,68.3450,66.976329,66.976329,66.976329,optimality,optimality,optimality,193.0,73.0,103,NaN,0.0000,0.0000,2146.422261,828.110392,1111.566530
19,2.0,2.0,2.0,10.0,10.0,10.0,56.8315,56.8315,56.8315,56.8315,56.8315,56.8315,56.112200,56.112200,56.112200,optimality,optimality,optimality,217.0,229.0,317,0.000000,0.0000,0.0000,4876.378629,3309.566905,5934.154851
20,2.0,2.0,2.0,1.0,1.0,1.0,77.0086,77.4101,77.0086,76.1752,76.0654,76.0315,75.925410,75.925410,75.925410,time_limit,time_limit,time_limit,21.0,12.0,10,0.833417,0.0177,0.0129,18819.067103,19615.192888,18157.721114
21,2.0,2.0,2.0,2.0,2.0,2.0,72.3306,72.3306,72.3306,71.8328,71.8388,71.8357,71.690912,71.690912,71.690912,time_limit,time_limit,time_limit,31.0,51.0,47,0.497849,0.0068,0.0069,18163.548048,18057.552010,18036.270230
22,2.0,2.0,2.0,3.0,3.0,3.0,85.1361,85.1361,85.1361,83.4756,83.4104,83.5487,83.321027,83.321027,83.321027,time_limit,time_limit,time_limit,17.0,14.0,13,1.660472,0.0207,0.0190,18990.388995,18117.444865,18093.805059
23,2.0,2.0,2.0,4.0,4.0,4.0,98.2632,96.3839,97.1235,94.2435,93.8346,93.8343,93.463645,93.463645,93.463645,time_limit,time_limit,time_limit,165.0,67.0,48,4.019654,0.0272,0.0351,18087.511350,18294.152509,18059.727471
24,2.0,2.0,2.0,5.0,5.0,5.0,67.1618,67.1618,67.1618,65.7460,65.7460,65.4449,65.444919,65.444919,65.444919,time_limit,time_limit,time_limit,26.0,24.0,6,1.415840,0.0215,0.0262,18003.990360,18215.081849,18048.154899
25,2.0,2.0,2.0,6.0,6.0,6.0,82.3995,82.3995,82.3995,82.3995,82.3995,82.3995,82.280425,82.280425,82.280425,optimality,optimality,optimality,23.0,13.0,19,0.000000,0.0000,0.0000,12703.955211,8925.012351,11054.698400
26,2.0,2.0,2.0,7.0,7.0,7.0,85.7051,85.7051,85.7051,85.7051,85.7051,85.7051,85.705102,85.705102,85.705102,optimality,optimality,optimality,1.0,1.0,1,0.000000,0.0000,0.0000,2599.996504,2907.864347,2098.492593
27,2.0,2.0,2.0,8.0,8.0,8.0,101.0588,102.6757,100.7241,97.3079,97.7487,97.6553,97.215845,97.215845,97.215845,time_limit,time_limit,time_limit,24.0,62.0,47,3.750976,0.0504,0.0314,18093.164832,19049.920735,18084.749815
28,2.0,2.0,2.0,9.0,9.0,9.0,80.5411,79.9510,79.0842,77.1573,76.6723,76.6723,76.487561,76.487561,76.487561,time_limit,time_limit,time_limit,36.0,15.0,13,3.383803,0.0428,0.0315,19197.754459,18662.743439,18058.738045
29,2.0,NaN,2.0,10.0,NaN,10.0,100.2608,NaN,99.8580,93.2255,NaN,93.2255,93.225512,NaN,93.225512,time_limit,NaN,time_limit,4.0,NaN,4,7.035324,NaN,0.0711,19847.754567,NaN,18155.935807

,instance_type_1,instance_type_2,instance_type_3,instance_id_1,instance_id_2,instance_id_3,bnb_upb_1,bnb_upb_2,bnb_upb_3,bnb_lwb_1,bnb_lwb_2,bnb_lwb_3,root_node_relaxObj_1,root_node_relaxObj_2,root_node_relaxObj_3,bnb_termCond_1,bnb_termCond_2,bnb_termCond_3,bnb_nodesExp_1,bnb_nodesExp_2,bnb_nodesExp_3,bnb_gap_1,bnb_gap_2,bnb_gap_3,bnb_wallTime_1,bnb_wallTime_2,bnb_wallTime_3
4,2.0,2.0,2.0,5.0,5.0,5.0,32.2911,32.1474,32.1474,31.8883,31.8883,32.1474,31.215928,31.215928,31.215928,queue_empty,queue_empty,optimality,225.0,197.0,147,0.402831,0.0081,0.0000,260.924808,214.093049,157.832005
10,2.0,2.0,2.0,1.0,1.0,1.0,46.4467,46.4467,46.4467,46.1730,46.1730,46.4467,46.172991,46.172991,46.172991,queue_empty,queue_empty,optimality,27.0,27.0,17,0.273695,0.0059,0.0000,1611.403424,1647.253790,1142.033178
17,NaN,2.0,2.0,NaN,8.0,8.0,NaN,78.1879,78.1879,NaN,78.1884,77.6935,NaN,75.261669,75.261669,NaN,optimality,time_limit,NaN,441.0,353,NaN,-0.0000,0.0064,NaN,3956.108821,7206.984518
29,2.0,NaN,2.0,10.0,NaN,10.0,100.2608,NaN,99.8580,93.2255,NaN,93.2255,93.225512,NaN,93.225512,time_limit,NaN,time_limit,4.0,NaN,4,7.035324,NaN,0.0711,19847.754567,NaN,18155.935807

In [68]:
cmp_inst = [1,2,3]
ref_columns_base = ['instance_type','instance_id']
ref_columns = [f"{r}_{i}" for r in ref_columns_base for i in cmp_inst]
comparing_columns_base = ['bnb_upb', 'bnb_lwb',
                     'root_node_relaxObj', 'bnb_termCond',
                     "bnb_nodesExp", "bnb_gap", "bnb_wallTime"]
comparing_columns = [f"{c}_{i}" for c in comparing_columns_base for i in cmp_inst]

print_full(pd.merge(pd.merge(results_df['mat_type_b_1'].add_suffix('_1', axis=1), results_df['mat_type_b_2'].add_suffix('_2', axis=1),how='inner',
         left_index=True, right_index=True), results_df['mat_type_b_3'].add_suffix('_3', axis=1), how='inner',
         left_index=True, right_index=True)[ref_columns+comparing_columns])

,instance_type_1,instance_type_2,instance_type_3,instance_id_1,instance_id_2,instance_id_3,bnb_upb_1,bnb_upb_2,bnb_upb_3,bnb_lwb_1,bnb_lwb_2,bnb_lwb_3,root_node_relaxObj_1,root_node_relaxObj_2,root_node_relaxObj_3,bnb_termCond_1,bnb_termCond_2,bnb_termCond_3,bnb_nodesExp_1,bnb_nodesExp_2,bnb_nodesExp_3,bnb_gap_1,bnb_gap_2,bnb_gap_3,bnb_wallTime_1,bnb_wallTime_2,bnb_wallTime_3
0,1.0,1.0,1.0,1.0,1.0,1.0,30.5054,30.5054,30.5054,30.5054,30.5054,30.5054,30.505350,30.505350,30.505350,optimality,optimality,optimality,1.0,1.0,1,0.000000,0.0000,0.0000,2.176990,2.055385,2.071534
1,1.0,1.0,1.0,2.0,2.0,2.0,32.5515,32.5515,32.5515,32.5515,32.5515,32.5515,32.551460,32.551460,32.551460,optimality,optimality,optimality,1.0,1.0,1,0.000000,-0.0000,-0.0000,1.505511,1.443200,1.459023
2,1.0,1.0,1.0,3.0,3.0,3.0,48.2343,48.2343,48.2343,48.2343,48.2343,48.2343,48.234318,48.234318,48.234318,optimality,optimality,optimality,1.0,1.0,1,0.000000,0.0000,0.0000,2.382779,2.294944,2.221706
3,1.0,1.0,1.0,4.0,4.0,4.0,34.0672,34.0672,34.0672,34.0672,34.0672,34.0672,33.814615,33.814615,33.814615,optimality,optimality,optimality,7.0,13.0,5,0.000000,0.0000,0.0000,5.741500,7.769908,4.545279
4,1.0,1.0,1.0,5.0,5.0,5.0,42.3825,42.3825,42.3825,42.3825,42.3825,42.3825,42.382521,42.382521,42.382521,optimality,optimality,optimality,1.0,1.0,1,0.000000,0.0000,0.0000,1.171003,1.090818,1.047617
5,1.0,1.0,1.0,6.0,6.0,6.0,37.9830,37.9830,37.9830,37.9830,37.9830,37.9830,37.982963,37.982963,37.982963,optimality,optimality,optimality,1.0,1.0,1,0.000000,0.0000,0.0000,3.766566,3.614295,3.607066
6,1.0,1.0,1.0,7.0,7.0,7.0,33.9802,33.9802,33.9802,33.9802,33.9802,33.9802,33.980242,33.980242,33.980242,optimality,optimality,optimality,1.0,1.0,1,0.000000,0.0000,0.0000,1.801703,1.717921,1.703597
7,1.0,1.0,1.0,8.0,8.0,8.0,33.3373,33.3373,33.3373,33.3373,33.3373,33.3373,33.337340,33.337340,33.337340,optimality,optimality,optimality,1.0,1.0,1,0.000000,0.0000,0.0000,2.238987,2.080077,2.137323
8,1.0,1.0,1.0,9.0,9.0,9.0,33.8996,33.8996,33.8996,33.8996,33.8996,33.8996,33.899644,33.899644,33.899644,optimality,optimality,optimality,1.0,1.0,1,0.000000,-0.0000,-0.0000,2.877857,2.746324,2.700721
9,1.0,1.0,1.0,10.0,10.0,10.0,39.2997,39.2997,39.2997,39.2997,39.2997,39.2997,39.299739,39.299739,39.299739,optimality,optimality,optimality,1.0,1.0,1,0.000000,-0.0000,-0.0000,1.493829,1.383993,1.414939
10,1.0,1.0,1.0,1.0,1.0,1.0,65.0004,65.0004,65.0004,65.0004,65.0004,65.0004,64.519714,64.519714,64.519714,optimality,optimality,optimality,67.0,41.0,69,0.000000,-0.0000,-0.0000,876.941156,586.068224,1100.621447
11,1.0,1.0,1.0,2.0,2.0,2.0,71.0608,71.0608,71.0608,71.0608,71.0608,71.0608,69.747532,69.747532,69.747532,optimality,optimality,optimality,15.0,11.0,17,0.000000,0.0000,0.0000,192.895364,133.752756,270.809679
12,1.0,1.0,1.0,3.0,3.0,3.0,74.2802,74.2802,74.2802,74.2802,74.2802,74.2802,73.886383,73.886383,73.886383,optimality,optimality,optimality,45.0,21.0,29,0.000000,-0.0000,-0.0000,1224.498055,811.690478,865.774235
13,1.0,1.0,1.0,4.0,4.0,4.0,58.4675,58.4675,58.4675,58.4675,58.4675,58.4675,58.322558,58.322558,58.322558,optimality,optimality,optimality,9.0,17.0,9,0.000000,0.0000,0.0000,384.012534,357.903630,420.779661
14,1.0,1.0,1.0,5.0,5.0,5.0,81.1285,81.1285,81.1285,81.1394,81.1394,80.6949,79.876270,79.876270,79.876270,optimality,optimality,time_limit,157.0,213.0,206,NaN,-0.0001,0.0054,1893.053401,1348.110265,7206.493745
15,1.0,1.0,1.0,6.0,6.0,6.0,57.9191,57.9191,57.9191,57.9191,57.9191,57.9191,57.919065,57.919065,57.919065,optimality,optimality,optimality,1.0,1.0,1,0.000000,0.0000,0.0000,741.973799,722.775486,728.852234
16,1.0,1.0,1.0,7.0,7.0,7.0,80.5727,81.5404,80.5727,80.3676,81.5404,80.5727,78.872826,78.872826,78.872826,queue_empty,optimality,optimality,91.0,157.0,91,0.205160,-0.0000,0.0000,982.030166,776.629272,998.888299
17,1.0,1.0,1.0,8.0,8.0,8.0,87.6911,87.7916,86.0280,86.6212,86.7973,86.0280,85.015936,85.015936,85.015936,time_limit,time_limit,optimality,434.0,750.0,179,1.069910,0.0115,0.0000,7211.361127,7201.863805,5617.701859
18,1.0,1.0,1.0,9.0,9.0,9.0,77.7821,77.7821,77.7821,77.7821,77.7821,77.7821,77.782090,77.782090,77.782090,optimality,optimality,optimality,1.0,1.0,1,0.000000,0.0000,0.0000,177.484702,174.848200,174.511679
19,1.0,1.0,1.0,10.0,10.0,10.0,68.4147,67.7015,67.7015,67.7037,67.7015,67.6778,67.018346,67.018346,67.018346,time_limit,optimality,time_limit,329.0,117.0,287,0.711024,0.0000,0.0004,7201.077157,2936.922555,7215.585262
20,1.0,1.0,1.0,1.0,1.0,1.0,101.2842,101.3013,101.1036,99.1980,99.2115,99.2004,99.156644,99.156644,99.156644,time_limit,time_limit,time_limit,12.0,14.0,14,2.086213,0.0211,0.0192,18710.510070,18286.368336,18277.872960
21,1.0,1.0,1.0,2.0,2.0,2.0,92.1706,92.1706,92.1706,92.1706,92.1706,92.1706,92.170631,92.170631,92.170631,optimality,optimality,optimality,1.0,1.0,1,0.000000,0.0000,0.0000,26695.457838,18710.126456,7971.656425
22,NaN,NaN,1.0,NaN,NaN,3.0,NaN,NaN,92.3350,NaN,NaN,91.4305,NaN,NaN,91.430494,NaN,NaN,time_limit,NaN,NaN,1,NaN,NaN,0.0099,NaN,NaN,19389.207410
23,1.0,1.0,1.0,4.0,4.0,4.0,109.1531,109.1531,109.1531,109.1531,109.1531,108.4670,108.279795,108.279795,108.279795,optimality,optimality,time_limit,123.0,113.0,38,0.000000,0.0000,0.0063,13600.812095,17978.110785,18111.762892
24,1.0,1.0,1.0,5.0,5.0,5.0,89.4479,89.4479,89.4479,89.4479,89.4479,89.4479,89.109677,89.109677,89.109677,optimality,optimality,optimality,111.0,103.0,55,0.000000,0.0000,0.0000,11843.016539,7575.104393,16559.539713
25,1.0,1.0,1.0,6.0,6.0,6.0,115.7811,115.7811,115.7811,115.7811,115.7811,115.7811,115.034619,115.034619,115.034619,optimality,optimality,optimality,27.0,35.0,17,0.000000,0.0000,0.0000,2972.423378,2543.968114,5220.675681
26,1.0,1.0,1.0,7.0,7.0,7.0,100.2466,100.2466,100.2466,100.2466,100.2466,100.2466,100.246614,100.246614,100.246614,optimality,optimality,optimality,1.0,1.0,1,0.000000,0.0000,0.0000,5490.697450,4076.461702,4935.921182
27,1.0,1.0,1.0,8.0,8.0,8.0,110.9727,110.9727,110.9727,110.3371,110.5659,110.5546,110.270169,110.270169,110.270169,time_limit,time_limit,time_limit,28.0,24.0,26,0.635583,0.0037,0.0038,18015.429878,19933.426219,18093.522670
28,1.0,1.0,1.0,9.0,9.0,9.0,99.0125,98.1090,97.2280,96.2614,96.4811,95.2710,94.691739,94.691739,94.691739,time_limit,time_limit,time_limit,189.0,334.0,60,2.751107,0.0169,0.0205,18218.984275,18021.462517,18037.588785
29,1.0,1.0,1.0,10.0,10.0,10.0,106.6453,106.6453,106.6453,106.6453,106.6453,106.6453,106.492646,106.492646,106.492646,optimality,optimality,optimality,5.0,3.0,3,0.000000,0.0000,0.0000,14131.777164,15756.082968,12552.061770

## Extract necessary results

In [ ]:
# compare phase 1 and phase 2 results
results_df['mat_type_a_3'].columns

Index(['instance_type', 'instance_id', 'distance_metric', 'total_demand',
       'dom_rule', 'truck_capacity', 'fixed_setup_time', 'truck_speed',
       'max_vehicles', 'max_nodes_proute_DP', 'max_vehicles_proute_DP',
       'init_max_nodes_proute', 'dp_mode', 'dp_time_limit', 'time_window',
       'tw_avg_factor', 'bnp_time_limit', 'model', 'experiment_id',
       'initial_node_relaxObj', 'initial_node_IPObj',
       'initial_node_relaxObj_in_min_per_pkg',
       'initial_node_IPObj_in_min_per_pkg', 'initial_node_remSpace',
       'initial_node_total_fleet_size', 'initial_node_node',
       'initial_node_gap', 'initial_node_wallTime', 'initial_node_dem_served',
       'root_node_relaxObj', 'root_node_IPObj',
       'root_node_relaxObj_in_min_per_pkg', 'root_node_IPObj_in_min_per_pkg',
       'root_node_remSpace', 'root_node_total_fleet_size', 'root_node_node',
       'root_node_gap', 'root_node_wallTime', 'root_node_dem_served',
       'best_node_relaxObj', 'best_node_IPObj',
       'best_node_relaxObj_in_min_per_pkg', 'best_node_IPObj_in_min_per_pkg',
       'best_node_remSpace', 'best_node_total_fleet_size', 'best_node_node',
       'best_node_gap', 'best_node_wallTime', 'best_node_dem_served',
       'bnb_sol_phase', 'bnb_termCond', 'bnb_upb', 'bnb_lwb',
       'bnb_upb_in_min_per_pkg', 'bnb_lwb_in_min_per_pkg', 'bnb_gap',
       'bnb_nodesExp', 'bnb_wallTime', 'bnb_bnpTimeLim'],
      dtype='object')

In [ ]:
comparing_columns = ['initial_node_IPObj_in_min_per_pkg', 'root_node_IPObj_in_min_per_pkg','best_node_IPObj_in_min_per_pkg']
results_df['mat_type_b_3']['init_to_root_diff'] = results_df['mat_type_b_3']['initial_node_IPObj_in_min_per_pkg'] - results_df['mat_type_b_3']['root_node_IPObj_in_min_per_pkg']
results_df['mat_type_b_3']['init_to_root_diff_perc'] = results_df['mat_type_b_3']['init_to_root_diff'] / results_df['mat_type_b_3']['initial_node_IPObj_in_min_per_pkg'] * 100
results_df['mat_type_b_3']['init_to_best_diff'] = results_df['mat_type_b_3']['initial_node_IPObj_in_min_per_pkg'] - results_df['mat_type_b_3']['best_node_IPObj_in_min_per_pkg']
results_df['mat_type_b_3']['init_to_best_diff_perc'] = results_df['mat_type_b_3']['init_to_best_diff'] / results_df['mat_type_b_3']['initial_node_IPObj_in_min_per_pkg'] * 100

results_df['mat_type_b_3'][comparing_columns+['init_to_root_diff','init_to_root_diff_perc','init_to_best_diff','init_to_best_diff_perc']]

,initial_node_IPObj_in_min_per_pkg,root_node_IPObj_in_min_per_pkg,best_node_IPObj_in_min_per_pkg,init_to_root_diff,init_to_root_diff_perc,init_to_best_diff,init_to_best_diff_perc
0,68.92,68.92,68.92,0.00,0.000000,0.00,0.000000
1,69.47,69.47,69.47,0.00,0.000000,0.00,0.000000
2,74.27,70.65,70.65,3.62,4.874108,3.62,4.874108
3,76.61,75.42,75.42,1.19,1.553322,1.19,1.553322
4,73.67,70.38,70.38,3.29,4.465861,3.29,4.465861
5,68.42,68.42,68.42,0.00,0.000000,0.00,0.000000
6,73.53,70.73,70.73,2.80,3.807970,2.80,3.807970
7,74.26,74.26,74.26,0.00,0.000000,0.00,0.000000
8,72.45,72.45,72.45,0.00,0.000000,0.00,0.000000
9,75.42,75.42,75.42,0.00,0.000000,0.00,0.000000
10,73.59,73.59,73.59,0.00,0.000000,0.00,0.000000
11,69.21,69.21,69.21,0.00,0.000000,0.00,0.000000
12,72.50,72.50,72.50,0.00,0.000000,0.00,0.000000
13,73.20,71.84,71.84,1.36,1.857923,1.36,1.857923
14,69.74,69.74,69.20,0.00,0.000000,0.54,0.774305
15,66.89,66.16,66.16,0.73,1.091344,0.73,1.091344
16,71.33,71.33,70.48,0.00,0.000000,0.85,1.191644
17,73.14,72.91,69.53,0.23,0.314465,3.61,4.935740
18,70.94,69.55,69.55,1.39,1.959402,1.39,1.959402
19,65.87,65.24,64.56,0.63,0.956429,1.31,1.988766
20,74.32,72.88,72.73,1.44,1.937567,1.59,2.139397
21,74.31,73.41,73.41,0.90,1.211143,0.90,1.211143
22,64.17,63.28,63.28,0.89,1.386941,0.89,1.386941
23,67.23,65.57,65.57,1.66,2.469136,1.66,2.469136
24,70.77,70.46,70.32,0.31,0.438039,0.45,0.635863
25,75.06,73.19,73.19,1.87,2.491340,1.87,2.491340
26,65.11,64.51,64.51,0.60,0.921517,0.60,0.921517
27,68.37,67.67,67.41,0.70,1.023841,0.96,1.404125
28,68.21,68.21,66.92,0.00,0.000000,1.29,1.891218
29,65.67,63.43,63.43,2.24,3.410994,2.24,3.410994

In [90]:
comparing_columns = ['initial_node_IPObj_in_min_per_pkg', 'root_node_IPObj_in_min_per_pkg','best_node_IPObj_in_min_per_pkg']
results_df['mat_type_a_3']['init_to_root_diff'] = results_df['mat_type_a_3']['initial_node_IPObj_in_min_per_pkg'] - results_df['mat_type_a_3']['root_node_IPObj_in_min_per_pkg']
results_df['mat_type_a_3']['init_to_root_diff_perc'] = results_df['mat_type_a_3']['init_to_root_diff'] / results_df['mat_type_a_3']['initial_node_IPObj_in_min_per_pkg'] * 100
results_df['mat_type_a_3']['init_to_best_diff'] = results_df['mat_type_a_3']['initial_node_IPObj_in_min_per_pkg'] - results_df['mat_type_a_3']['best_node_IPObj_in_min_per_pkg']
results_df['mat_type_a_3']['init_to_best_diff_perc'] = results_df['mat_type_a_3']['init_to_best_diff'] / results_df['mat_type_a_3']['initial_node_IPObj_in_min_per_pkg'] * 100

results_df['mat_type_a_3'][comparing_columns+['init_to_root_diff','init_to_root_diff_perc','init_to_best_diff','init_to_best_diff_perc']]

,initial_node_IPObj_in_min_per_pkg,root_node_IPObj_in_min_per_pkg,best_node_IPObj_in_min_per_pkg,init_to_root_diff,init_to_root_diff_perc,init_to_best_diff,init_to_best_diff_perc
0,52.04,47.85,47.85,4.19,8.051499,4.19,8.051499
1,59.30,57.97,57.97,1.33,2.242833,1.33,2.242833
2,53.06,53.06,53.06,0.00,0.000000,0.00,0.000000
3,60.29,60.29,60.29,0.00,0.000000,0.00,0.000000
4,56.22,54.73,53.38,1.49,2.650302,2.84,5.051583
5,58.41,56.80,56.80,1.61,2.756377,1.61,2.756377
6,57.59,53.24,53.24,4.35,7.553395,4.35,7.553395
7,51.10,51.10,51.10,0.00,0.000000,0.00,0.000000
8,58.91,57.64,57.64,1.27,2.155831,1.27,2.155831
9,60.85,58.21,58.21,2.64,4.338537,2.64,4.338537
10,55.18,52.58,52.58,2.60,4.711852,2.60,4.711852
11,60.66,59.18,59.18,1.48,2.439829,1.48,2.439829
12,59.17,58.13,57.58,1.04,1.757647,1.59,2.687173
13,59.31,58.48,58.48,0.83,1.399427,0.83,1.399427
14,58.04,58.04,58.02,0.00,0.000000,0.02,0.034459
15,56.71,54.38,54.38,2.33,4.108623,2.33,4.108623
16,60.66,58.91,58.91,1.75,2.884932,1.75,2.884932
17,64.02,63.46,63.19,0.56,0.874727,0.83,1.296470
18,64.43,61.11,61.11,3.32,5.152879,3.32,5.152879
19,55.03,54.20,54.20,0.83,1.508268,0.83,1.508268
20,57.26,55.95,55.39,1.31,2.287810,1.87,3.265805
21,58.97,57.61,57.61,1.36,2.306257,1.36,2.306257
22,59.85,58.35,58.35,1.50,2.506266,1.50,2.506266
23,60.33,59.03,58.34,1.30,2.154815,1.99,3.298525
24,54.56,52.80,52.80,1.76,3.225806,1.76,3.225806
25,60.36,57.31,57.31,3.05,5.053015,3.05,5.053015
26,57.07,55.15,55.15,1.92,3.364289,1.92,3.364289
27,62.79,60.36,60.36,2.43,3.870043,2.43,3.870043
28,56.67,55.03,54.43,1.64,2.893947,2.24,3.952709
29,59.39,59.39,59.39,0.00,0.000000,0.00,0.000000